create table resposta
(
    id           bigint generated by default as identity,
    data_criacao timestamp,
    mensagem     varchar(255),
    solucao      boolean,
    autor_id     bigint,
    topico_id    bigint,
    primary key (id)
);

alter table resposta
    add constraint FK9999kvnmdq63ah7imctrl06r7
        foreign key (autor_id)
            references usuario;

alter table resposta
    add constraint FKltuv9rkfjtlmn8b0rb3wdbjsv
        foreign key (topico_id)
            references topico;